dist: trusty
language: python
python:
- '3.6'
install:
- pip install tox-travis
script:
- tox -r
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  user: thclark
  password:
    secure: ESECVIKAg6+gio4H6t8g2vS1Zirqc0Ocr2OxZFAiaD5iYa2WVdISu20XCJXG5iLHZVt0BwlTOV31sDaBFTJfpwqVjG0/2fhJgwDAlOYyH6ZuBJMaz/H7Xd+YVXPVME8q0uNls6+jXZ3WjkRYVZ1BvWUG0B7d2kF5C2d03CZUmUUNzIyitR1ofrVKY6tuH16aaym9wDDm7YVRW5vkM/VnY2lhHcEWx9KJTATYCHKxY7CUqhyeaP3l3r9JB4bjS+Bp6XNrIC1dknEJ8dUEak8oAs0csqvPKfnlQTq65RYX3kyvPKjzDl5MH9Q89+GGRQ82jeU1jT0S0hhHfcb/k3uoPB0hfaFhQhZLh5N5FIlQ9T4KD5Afpk1VYW+viFkqUhMXm67pb8yn2tYb0lPISzhgZ/pEd64lEDbvQSYdxTOuaL+G/NBcloipwToYbAYG5M+LH5oj8KgJXyyhg+5/gi57Wet5EfdIFEFVGqJuDT655g250gFxk5CHNvKe4Gsc3PBhZNvUeRij/y4Lt3n4STyBT7PwMcPkCb2z7Y7lCHaaPP3rT7+IhWMhNFiCx8b5AhTCyPG+0VOlHZ6Vko0C711iNyPk6K/YThnJo4b1J9npcgz+awJt6PnjMyUt5DSmkzT7zXbpK5Q3L0Vl9VfwioS0ZVqJSYsg0rBgmI7jAphJbyI=
  on:
    branch: master
