dist: trusty
language: python
python:
- '3.6'
install:
- pip install tox-travis
script:
- tox -r
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  user: thclark
  password:
    secure: Kifszxg0DrBzRAFfQIROM6IwXXt1bmpFpEJndabWJUSNp0dpznulSBdh9LvpWH/dU2YHboKtcKlieslXPe7dn1Ij1Z51lUlGIlbfvJX5s/eTCjfVikx6b9kPavd2Mehl1jyKsjGMG2zhZILuSgVS5XPAIkB0luYlIXNpfdUVBKpXVDcwXZDdPvMmGJYkEYTj2MDAI1TTZeHcQ97f2XtrE7qU3M9UKB3ehllIGWlePszTTfJeXNOALHMh60fkOXEVaiSzxMXTCJpRsPJ7p1TxUl3HkiSqELTCwqtd+cNFEAS5zVDKfDzp9evIlhRIphDdLhlIXKFDjRIKsv3ac2Zixa9srFwwJjr3s1VnO/rBCJZhlfy4xNbtPGdZ/KwveGyu3dMdRG/k3ak+8FYLJEYzy+PZjn7wifGMy2QIFipDa83Jfma0J7xXi9nBj3UzmJS6nSB6P6wjHbv/EOpAS1GUPsZDgBU54l5tlcVmNzg/CzHPy76pe18TNz9dSbxTjX8GVsLWOzl+3xbwNfE7KWVLxcxu1qzUlj2IqMAnfk9bw0aNIYRDBMhtV/7Q+HSK0mY+8VlUD6qqW0weYJKFM6PFypSpE18lO8wW6/ZLReyjiI8nzqxSkRJNta3pCiwHaRscWJI7HCSjwNFdahduKGVEKhIWqqL/rimTx6Pfu2YEkMc=
  on:
    branch: master
